// Code generated by "stringer -type=FileType"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Config-1]
	_ = x[Key-2]
	_ = x[Pack-4]
}

const (
	_FileType_name_0 = "ConfigKey"
	_FileType_name_1 = "Pack"
)

var (
	_FileType_index_0 = [...]uint8{0, 6, 9}
)

func (i FileType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FileType_name_0[_FileType_index_0[i]:_FileType_index_0[i+1]]
	case i == 4:
		return _FileType_name_1
	default:
		return "FileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
