name: Validation


on:
  workflow_dispatch:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      - name: Go Vet
        run: go vet ./...
      - name: Go Tidy
        run: go mod tidy && git diff --exit-code
      - name: Go Mod
        run: go mod download
      - name: Go Mod Verify
        run: go mod verify
      - name: Go Get
        run: go get ./...
      - name: Go Generate
        run: go generate ./... && git diff --exit-code
      - name: Go Build
        run: go build -v ./...
      - name: Go Test
        run: go test ./...
